### ISSUE TITLE
title of the mod is not gluten free

### ISSUE THREAD

**Issue by Ueaj-Kerman** [Draylar/gluten-free#1]
title of the mod is not gluten free

**Comment by Draylar** [comment]
google how to delete gihub comment

**Comment by Draylar** [comment]
delete comment github

**Comment by Draylar** [comment]
google cant delete github comment

**Comment by Draylar** [comment]
how to close github issue google

**Comment by Ueaj-Kerman** [comment]
title of the mod is not gluten free

**Comment by Ueaj-Kerman** [comment]
how to reopen issue goolge

**Comment by Ueaj-Kerman** [comment]
google issue reopen github
